name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    collapse-after: 5
    label: 'feature'
  - title: '🐛 Bug Fixes'
    collapse-after: 5
    label: 'bug'
  - title: '🧰 Dependency Changes'
    collapse-after: 5
    label: 'dependency'
  - title: '⚡ Workflow Changes'
    collapse-after: 5
    label: 'workflow'
  - title: '📝 Documentation Changes'
    collapse-after: 5
    label: 'documentation'

autolabeler:
  - label: 'feature'
    body: 
      - '/feature/'
    title: 
      - '/feature/'
  - label: 'bug'
    body: 
      - '/bug/'
      - '/bugfix/'
    title: 
      - '/bug/'
      - '/bugfix/'
  - label: 'dependency'
    body: 
      - '/dependency/'
    title: 
      - '/dependency/'
  - label: 'workflow'
    body: 
      - '/workflow/'
    title: 
      - '/workflow/'
  - label: 'documentation'
    body: 
      - '/documentation/'
    title: 
      - '/documentation/'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 

template: |
  ## ➕ Changes

  $CHANGES