name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Added Features'
    collapse-after: 3
    label: 'feature'
  - title: '🔑 Better Security'
    collapse-after: 3
    label: 'security'
  - title: '🐛 Bug Fixes'
    collapse-after: 3
    label: 'bug'
  - title: '🐢 Optimization'
    collapse-after: 3
    label: 'optimization'
  - title: '🧰 Dependency Changes'
    collapse-after: 3
    label: 'dependency'
  - title: '⚡ Workflow Changes'
    collapse-after: 3
    label: 'workflow'
  - title: '📝 Documentation Changes'
    collapse-after: 3
    label: 'documentation'

autolabeler:
  # Label: Feature -------------------------
  - label: 'feature'
    body: 
      - '/feature/'
    title: 
      - '/feature/'

  # Label: Security -------------------------
  - label: 'security'
    body: 
      - '/security/'
      - '/CVE/'
    title: 
      - '/security/'
      - '/CVE/'

  # Label: Bug -------------------------
  - label: 'bug'
    body: 
      - '/bug/'
      - '/bugfix/'
    title: 
      - '/bug/'
      - '/bugfix/'
      - '/error/'

  # Label: Optimization -------------------------
  - label: 'optimization'
    body:
      - '/optimization/'
      - '/performance/'
    title: 
      - '/optimization/'
      - '/performance/'

  # Label: Dependency -------------------------
  - label: 'dependency'
    body: 
      - '/dependency/'
      - '/dependabot/'
    title: 
      - '/dependency'
      - '/dependabot/'
      - '/bump'

  # Label: Workflow -------------------------
  - label: 'workflow'
    body: 
      - '/workflow/'
      - '/yaml/'
    title: 
      - '/workflow/'
      - '/yaml/'

  # Label: Documentation -------------------------
  - label: 'documentation'
    body: 
      - '/documentation/'
      - '/.md/'
    title: 
      - '/documentation/'
      - '/.md/'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 

template: |
  ## 🔆 What changed?

  $CHANGES