name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Dependency Update'
    label: 'dependency'
  - title: '⚡ Workflow Update'
    label: 'workflow'

autolabeler:
  - label: 'feature'
    body: 
      - '/feature/'
    title: 
      - '/feature/'
  - label: 'bug'
    body: 
      - '/bug/'
      - '/bugfix/'
    title: 
      - '/bug/'
      - '/bugfix/'
  - label: 'dependency/'
    body: 
      - '/dependency/'
    title: 
      - '/dependency'
  - label: 'workflow'
    body: 
      - '/workflow/'
    title: 
      - '/workflow/'


  

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 

template: |
  ## Changes

  $CHANGES