name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Dependency Update'
    label: 'dependency'
  - title: '⚡ Workflow Update'
    label: 'workflow'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 

autolabeler:
  - label: 'bug'
    title: 'bug'
  - label: 'feature'
    title: 'feature'
  - label: 'dependency'
    title: 'dependency'
  - label: 'workflow'
    title: 'workflow'

template: |
  ## Changes

  $CHANGES