name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Dependency Update'
    label: 'dependency'
  - title: '⚡ Workflow Update'
    label: 'workflow'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 

autolabeler:
  - label: 'feature'
    body:
      - '/feature/'
    title:
      - '/feature/'
  - label: 'bug'
    body:
      - '/bug/'
    title:
      - '/bug/'
  - label: 'dependency'
    body:
      - '/dependency/'
    title:
      - '/dependency/'
  - label: 'workflow'
    body:
      - '/workflow/'
    title:
      - '/workflow/'

template: |
  ## Changes

  $CHANGES