name: black

on:
    push:
      branches:
        - master
        - master-patch
      paths-ignore: 
        - 'development/**'
  
    pull_request:
      paths-ignore:
        - 'development/**'
        

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: ". -v"
          version: "~= 22.0"