# https://beta.ruff.rs
name: ruff
on:
  push:
    branches:
      - master
      - dev
    paths-ignore: 
      - 'development/**'

  pull_request:
    paths-ignore:
      - 'development/**'
      
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user ruff
    - run: ruff check . -v --fix

