# https://beta.ruff.rs
name: ruff
on:
  pull_request:
    branches:
      - master
      - master-patch
    paths-ignore: 
      - 'development/**'
  push:
    branches:
      - master
    paths-ignore: 
      - 'development/**'
      
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user ruff
    - run: ruff check . -v --fix

