# https://beta.ruff.rs
name: ruff
on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'development/**'

  pull_request:
    paths-ignore:
      - 'development/**'
      
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user ruff
    - run: ruff check . -v --fix

